name: CI - Jest Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Add .env variables (if needed)
    - name: Set up environment variables
      run: |
        echo "JWT_SECRET=test_secret" > .env
        echo "DATABASE_URL=test_database_url" >> .env

    # Step 5: Run tests
    - name: Run Jest tests
      run: npm test
