name: CI - Jest Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          dev_password: ${{ secrets.DB_PASSWORD }}
          dev_database: ${{ secrets.DB_DATABASE }}
        ports:
          - 3306:3306
        env:          
          dev_host: ${{ secrets.DB_HOST }}
          dev_user: ${{ secrets.DB_USER }}
          dev_password: ${{ secrets.DB_PASSWORD }}
          dev_database: ${{ secrets.DB_DATABASE }}
          dev_port: ${{ secrets.DB_PORT }}
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test
